Add important missing part of README.
aristocrates/molec pull request #1
Opened 2019-06-03 18:45 UTC by ksbrar

The world must know who authored this beautiful repo.

2019-06-07 03:29 UTC, aristocrates requested changes

2019-06-07 03:29 UTC, aristocrates commented on README
> +Noble gas simulation using the Lennard-Jones potential by **Nickolas Dickolas of Penisshire**.
```suggestion
Noble gas simulation using the Lennard-Jones potential.
```

2019-06-07 03:29 UTC, aristocrates commented on README
>  =====
```suggestion
```

2019-06-07 03:29 UTC, aristocrates commented on README
>  molec
```suggestion
# molec
```

2019-06-07 03:29 UTC, aristocrates commented on README
```suggestion
## Nicholas Meyer

```

2019-06-07 05:06 UTC, ksbrar commented on README
> +Noble gas simulation using the Lennard-Jones potential by **Nickolas Dickolas of Penisshire**.
I strongly disagree with this change.

2019-06-07 05:07 UTC, ksbrar commented on README
Redundant. Sad!

2019-06-11 23:47 UTC, ksbrar commented
Reconsider your changers, Sir Nicholas.

2019-08-12 19:51 UTC, ksbrar commented
Disappointed in the slow response times for this project. Closing my PR and taking it somewhere else. 0/10 even with rice.

2019-08-12 19:51 UTC, closed without merging